In [1]:
from data_collection.data_collection import *
from shimi import *

# Load Shimi
shimi = Shimi(silent=True)

# Load data collector class
collector = DataCollector(False)

Listening to Max on ('127.0.0.1', 8003)
If the camera is not on, please run turn_on_camera().


In [92]:
SUBJECT_NUMBER = 0
GESTURE_NUMBER = 1
POSITION = 0

In [ ]:
collector.record_new_video_gesture(SUBJECT_NUMBER, GESTURE_NUMBER, POSITION, duration=4.0)

In [93]:
collector.play_video_gesture(SUBJECT_NUMBER, GESTURE_NUMBER, POSITION)

Finding video...
Playing 0_1_0_101118_163845.mov...


In [ ]:
collector.turn_on_camera()

In [ ]:
collector.turn_off_camera()

In [87]:
r_torso_neck = collector.record_new_shimi_gesture(shimi, SUBJECT_NUMBER, GESTURE_NUMBER, POSITION)

Finding video...
3.0...
2.0...
1.0...
Recording...
Done. Recorded 1094 positions and 1094 velocities.


In [41]:
r_torso_neck.play()

In [89]:
r_foot_hand = collector.record_new_shimi_gesture(shimi, SUBJECT_NUMBER, GESTURE_NUMBER, POSITION, motors=[shimi.foot, shimi.phone])

Finding video...
3.0...
2.0...
1.0...
Recording...
Done. Recorded 1632 positions and 1632 velocities.


In [33]:
r_foot_hand.play()

In [90]:
r_torso_neck.add_recording(r_foot_hand)

In [91]:
collector.save_shimi_gesture(r_torso_neck, SUBJECT_NUMBER, GESTURE_NUMBER, POSITION)

In [36]:
collector.play_video_and_shimi(shimi, SUBJECT_NUMBER, GESTURE_NUMBER, POSITION)

Finding shimi gesture...
Finding video...
Starting motion, calling back...


In [88]:
collector.play_video_and_shimi(shimi, SUBJECT_NUMBER, GESTURE_NUMBER, POSITION, recorder=r_torso_neck)

Finding video...
Starting motion, calling back...


In [59]:
shimi.initial_position()

In [60]:
shimi.disable_torque()

In [99]:
t = (1, 2, 3, 4)
for i, v in enumerate(t):
    print(i, v)

0 1
1 2
2 3
3 4


In [113]:
t = []
a = [1, 2, 3, 4, 5, 6, 7]
for i in range (12):
    t.append(a)
# print(np.array(t).T.shape)
t1 = np.array(t).T
t2 = np.array(t).T
t3 = np.empty((7,1))
c = np.concatenate((t1, t2), axis=1)
print(c)
t3 = np.concatenate((t3, t2), axis=1)
print(t3)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]]
[[4.e-323 1.e+000 1.e+000 1.e+000 1.e+000 1.e+000 1.e+000 1.e+000 1.e+000
  1.e+000 1.e+000 1.e+000 1.e+000]
 [0.e+000 2.e+000 2.e+000 2.e+000 2.e+000 2.e+000 2.e+000 2.e+000 2.e+000
  2.e+000 2.e+000 2.e+000 2.e+000]
 [0.e+000 3.e+000 3.e+000 3.e+000 3.e+000 3.e+000 3.e+000 3.e+000 3.e+000
  3.e+000 3.e+000 3.e+000 3.e+000]
 [0.e+000 4.e+000 4.e+000 4.e+000 4.e+000 4.e+000 4.e+000 4.e+000 4.e+000
  4.e+000 4.e+000 4.e+000 4.e+000]
 [0.e+000 5.e+000 5.e+000 5.e+000 5.e+000 5.e+000 5.e+000 5.e+000 5.e+000
  5.e+000 5.e+000 5.e+000 5.e+000]
 [0.e+000 6.e+000 6.e+000 6.e+000 6.e+000 6.e+000 6.e+000 6.e+000 6.e+000
  6.e+000 6.e+000 6.e+0

In [119]:
[0.1 * i for i in range(int(4.0 / 0.01)]

SyntaxError: invalid syntax (<ipython-input-119-2aa10f7734c0>, line 1)